[project]
name = "gpumonitoring"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["prometheus-client==0.23.1", "pyhumps==3.8.0"]
